name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: fedora:42
    steps:

      - name: Install dependencies
        run: |
          yum install -y git ImageMagick-devel sbcl wget

      - name: Install Quicklisp
        run: |
          cd
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --disable-debugger --load ~/quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit

      - name: Clone
        run: |
          cd ~/quicklisp/local-projects
          git clone --depth=1 https://github.com/ruricolist/lisp-magick-wand.git

      - name: Load lisp-magic-wand
        run: |
          sbcl --disable-debugger --load ~/quicklisp/setup.lisp --eval '(ql:register-local-projects)' --eval '(ql:quickload :lisp-magick-wand)' --quit
