name: CI

on: [push, pull_request]

env:
  DYNAMIC_SPACE_SIZE_MB: '16384'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: fedora:42
    steps:

      - name: Install dependencies
        run: |
          yum install -y ImageMagick-devel sbcl wget

      - name: Install Quicklisp
        run: |
          cd
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --disable-debugger --load ~/quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit

      - name: Clone
        uses: actions/checkout@v4

      - name: Load lisp-magic-wand
        run: |
          export CL_SOURCE_REGISTRY="$(pwd):"
          sbcl \
          --dynamic-space-size ${DYNAMIC_SPACE_SIZE_MB} \
          --disable-debugger \
          --load ~/quicklisp/setup.lisp \
          --eval '(ql:register-local-projects)' \
          --eval '(ql:quickload :lisp-magick-wand)' \
          --quit

      - name: Test lisp-magic-wand
        run: |
          export CL_SOURCE_REGISTRY="$(pwd):"
          sbcl \
          --dynamic-space-size ${DYNAMIC_SPACE_SIZE_MB} \
          --disable-debugger \
          --load ~/quicklisp/setup.lisp \
          --eval '(ql:register-local-projects)' \
          --eval '(ql:quickload :lisp-magick-wand/test)' \
          --eval '(setf fiveam:*on-failure* :debug)' \
          --eval '(asdf:test-system :lisp-magick-wand)' \
          --quit
